package com.example.viewpagerwithfragments;

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.support.v4.app.FragmentActivity;
import android.support.v4.app.FragmentPagerAdapter;
import android.support.v4.view.ViewPager;

/*
 * ViewPager is a layout manager that allows the user to flip left and right through pages of data. 
 * The pages that the view shows are generated by using an implementation of a PagerAdapter.
 */
public class ViewPagerWithFragments extends FragmentActivity {
	
	private int NUM_PAGES = 3;

	/** Called when the activity is first created. */
	@Override
	public void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_view_pager_with_fragments);

		//Retrieve the ViewPager and set adapter to it
		ViewPager myPager = (ViewPager) findViewById(R.id.pager);
		myPager.setAdapter(new MyPagerAdapter(getSupportFragmentManager()));
		myPager.setCurrentItem(1);
	}
	
	//  An implementation of FragmentPagerAdapter to facilitate the use of Fragments in a ViewPager
	//	FragmentPagerAdapter: Implementation of PagerAdapter that represents each page as a Fragment 
	//	that is persistently kept in the fragment manager as long as the user can return to the page.
	private class MyPagerAdapter extends FragmentPagerAdapter{
		public MyPagerAdapter(android.support.v4.app.FragmentManager fragmentManager){
			super(fragmentManager);
		}

		//	Return the Fragment associated with a specified position.		
		@Override
		public Fragment getItem(int position) {
			System.out.println("get : " + position);
			switch(position){
			case 0:
				return new Page1Fragment();
			case 1:
				return new Page2Fragment();
			case 2:
				return new Page3Fragment();
			default:
				return null;
			}
		}

		//	Return the number of views available.
		@Override
		public int getCount() {
			return NUM_PAGES;
		}
	}
}
